// Code generated by go-swagger; DO NOT EDIT.

package apiversion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAPIVersionHandlerFunc turns a function with the right signature into a get API version handler
type GetAPIVersionHandlerFunc func(GetAPIVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIVersionHandlerFunc) Handle(params GetAPIVersionParams) middleware.Responder {
	return fn(params)
}

// GetAPIVersionHandler interface for that can handle valid get API version params
type GetAPIVersionHandler interface {
	Handle(GetAPIVersionParams) middleware.Responder
}

// NewGetAPIVersion creates a new http.Handler for the get API version operation
func NewGetAPIVersion(ctx *middleware.Context, handler GetAPIVersionHandler) *GetAPIVersion {
	return &GetAPIVersion{Context: ctx, Handler: handler}
}

/*GetAPIVersion swagger:route GET /apiversion apiversion getApiVersion

Return the bunkerhill version

*/
type GetAPIVersion struct {
	Context *middleware.Context
	Handler GetAPIVersionHandler
}

func (o *GetAPIVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAPIVersionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
