// Code generated by go-swagger; DO NOT EDIT.

package apiversion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bbcyyb/bunkerhill/models"
)

// GetAPIVersionOKCode is the HTTP code returned for type GetAPIVersionOK
const GetAPIVersionOKCode int = 200

/*GetAPIVersionOK Successful response

swagger:response getApiVersionOK
*/
type GetAPIVersionOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetAPIVersionOKBody `json:"body,omitempty"`
}

// NewGetAPIVersionOK creates GetAPIVersionOK with default headers values
func NewGetAPIVersionOK() *GetAPIVersionOK {

	return &GetAPIVersionOK{}
}

// WithPayload adds the payload to the get Api version o k response
func (o *GetAPIVersionOK) WithPayload(payload *models.GetAPIVersionOKBody) *GetAPIVersionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api version o k response
func (o *GetAPIVersionOK) SetPayload(payload *models.GetAPIVersionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIVersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIVersionInternalServerErrorCode is the HTTP code returned for type GetAPIVersionInternalServerError
const GetAPIVersionInternalServerErrorCode int = 500

/*GetAPIVersionInternalServerError Internal Server Error

swagger:response getApiVersionInternalServerError
*/
type GetAPIVersionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewGetAPIVersionInternalServerError creates GetAPIVersionInternalServerError with default headers values
func NewGetAPIVersionInternalServerError() *GetAPIVersionInternalServerError {

	return &GetAPIVersionInternalServerError{}
}

// WithPayload adds the payload to the get Api version internal server error response
func (o *GetAPIVersionInternalServerError) WithPayload(payload *models.GenericError) *GetAPIVersionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api version internal server error response
func (o *GetAPIVersionInternalServerError) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIVersionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
