version: "3"
services:
  bunkerhill-server:
    build: .
    image: bunkerhill-server-alpine
    container_name: bunkerhill-server
    links:
      - mongodb
    ports:
      - 3030:3030
  mongodb:
    image: mongo:3.4.14-jessie 
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db/mongodb:/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
