swagger: '2.0'
basePath: "/api"
info:
  title: "Bunker Hill a"
  description: "RestAPI supporting lifecycle management for blog system named Missouri"
  version: "0.0.1"
tags:
- name: "apiversion"
  description: "Restful API Version"
- name: "blog"
  description: "Article information in blog"
paths:
  /apiversion:
    get:
      tags:
      - "apiversion"
      summary: "Return the bunkerhill version"
      produces:
      - "application/json"
      operationId: "getAPIVersion"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/apiversion"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/generic.error'
      
  /blog:
    get:
      tags:
      - "blog"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        required: false
        type: "string"
        in: "query"
        description: "defaults to World if not given"
      operationId: "getBlog"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/blogs"
              paging:
                $ref: "#/definitions/paging"
   
definitions:
  apiversion:
    type: "object"
    properties:
       apiVersion:
        type: "string"
    required:
    - "apiVersion"
  blogs:
    type: "array"
    items:
      $ref: "#/definitions/blog"
  paging:
    type: "object"
    properties:
      previous:
        type: "string"
        format: "uri"
      next:
        type: "string"
        format: "uri"
  blog:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      title:
        type: "string"
      body:
        type: "string"
      body_html:
        type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      author: 
        $ref: "#/definitions/author"
      comments:
        $ref: "#/definitions/comment"
  author:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
  comment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
  generic.error:
    type: "object"
    properties:
      message:
        type: "string"
  generic.deleteResponse:
    type: "object"
    properties:
      id:
        type: "string"
      message:
        type: "string"