---

swagger: '2.0'
basePath: "/api"
info:
  title: "Bunker Hill"
  description: "RestAPI supporting lifecycle management for blog system named Missouri"
  version: "0.0.1"
paths:
  /blog:
    get:
      produces:
      - text/plain
      parameters:
      - name: name
        required: false
        type: string
        in: query
        description: defaults to World if not given
      operationId: getBlog
      responses:
        200:
          description: returns all blogs
          schema:
            type: string
            description: contains the actual blog as plain text

definitions:
  apiversion:
    type: "object"
    properties:
      apiVersion:
        type: "string"
    required:
    - apiVersion
  blog:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
