swagger: '2.0'
basePath: "/api/v1"
info:
  title: "Bunker Hill"
  description: "RestAPI supporting lifecycle management for blog system named Missouri"
  version: "0.0.1"
tags:
- name: "apiversion"
  description: "Restful API Version"
- name: "blog"
  description: "Article information in blog"
paths:
  /apiversion:
    get:
      tags:
      - "apiversion"
      summary: "Return the bunkerhill version"
      produces:
      - "application/json"
      operationId: "GetAPIVersion"
      responses:
        200:
          description: "Successful response"
          schema:
              type: "object"
              properties:
                data:
                  $ref: "#/definitions/apiversion"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
  /blogs:
    get:
      tags:
      - "blog"
      produces:
      - "application/json"
      parameters:
      - name: "author_id"
        required: false
        type: "string"
        in: "query"
      - name: "page"
        required: false
        type: "integer"
        format: "int32"
        in: "query"
      - name: "pre_page"
        required: false
        type: "integer"
        format: "int32"
        in: "query"
      - name: "sortby"
        required: false
        type: "string"
        in: "query"
        description: "e.g. sortby=+title,-timestamp"
      - name: "select"
        required: false
        type: "string"
        in: "query"
        description: "e.g. select=title,id,body,body_html"
      operationId: "GetBlogs"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/blog"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/generic.error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
    post:
      tags:
      - "blog"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "blog"
        in: "body"
        description: "Content of blog to be saved"
        required: true
        schema:
          $ref: "#/definitions/blog"
      operationId: "InsertBlog"
      responses:
        201:
          description: "The request has been fulfilled, resulting in the creation of a new resource."
          schema:
            $ref: "#/definitions/blog"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/generic.error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
  /blogs/{blogId}:
    get:
      tags:
      - "blog"
      produces:
      - "application/json"
      parameters:
      - name: "blogId"
        description: "Id of the blog to return"
        required: true
        type: "string"
        in: "path"
      operationId: "GetBlogById"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/blog"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/generic.error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
    put:
      tags:
      - "blog"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "blogId"
        description: "Id of the blog to update"
        required: true
        type: "string"
        in: "path" 
      - name: "blog"
        description: "Content of blog to be saved"
        required: true
        in: "body"
        schema:
          $ref: "#/definitions/blog"
      operationId: "UpdateBlog"
      responses:
        200:
          description: "Successful response"
          schema: 
            $ref: "#/definitions/blog"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/generic.error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
    delete:
      tags:
      - "blog"
      produces:
      - "application/json"
      parameters:
      - name: "blogId"
        description: "Id of the blog to delete"
        required: true
        type: "string"
        in: "path" 
      operationId: "DeleteBlog"
      responses:
        200:
          description: "Successful response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/generic.error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/generic.error"
definitions:
  apiversion:
    type: "object"
    properties:
      apiVersion:
        type: "string"
    required:
    - "apiVersion"
  blog:
    type: "object"
    properties:
      id:
        type: "string"
      title:
        type: "string"
      body:
        type: "string"
      body_html:
        type: "string"
      timestamp:
        type: "string"
      author: 
        $ref: "#/definitions/user"
      comment_ids:
          type: "array"
          items:
              type: "string"
  user:
    type: "object"
    properties:
      id:
        type: "string"
  comment:
    type: "object"
    properties:
      id:
        type: "string"
      body:
        type: "string"
      body_html:
        type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      post_id:
        type: "integer"
        format: "int32"
      author:
        $ref: "#/definitions/user"
  generic.error:
    type: "object"
    properties:
      message:
        type: "string"
  generic.deleteResponse:
    type: "object"
    properties:
      id:
        type: "string"
      message:
        type: "string"
