// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBlogOKCode is the HTTP code returned for type GetBlogOK
const GetBlogOKCode int = 200

/*GetBlogOK returns all blogs

swagger:response getBlogOK
*/
type GetBlogOK struct {

	/*contains the actual blog as plain text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetBlogOK creates GetBlogOK with default headers values
func NewGetBlogOK() *GetBlogOK {

	return &GetBlogOK{}
}

// WithPayload adds the payload to the get blog o k response
func (o *GetBlogOK) WithPayload(payload string) *GetBlogOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blog o k response
func (o *GetBlogOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
