// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Bunker Hill
RestAPI supporting lifecycle management for blog system named Missouri


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
