// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Bunker Hill",
    "version": "0.0.1"
  },
  "paths": {
    "/blog": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getBlog",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns all blogs",
            "schema": {
              "description": "contains the actual blog as plain text",
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Bunker Hill",
    "version": "0.0.1"
  },
  "paths": {
    "/blog": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getBlog",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns all blogs",
            "schema": {
              "description": "contains the actual blog as plain text",
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
}
