FROM golang:1.10.1

WORKDIR /go/src/github.com/bbcyyb/bunkerhill

COPY bin /bin

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 \
  && echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list \
  && apt-get update \
  && apt-get install -y mongodb-org mongodb-org-shell mongodb-org-server mongodb-org-mongos mongodb-org-tools libssl1.0.0

RUN /bin/bunkerhill_build_linux_dev.sh

ENTRYPOINT ["bin/bunkerhill_entrypoint_linux_dev.sh"]
