version: "3"
services:
  bunkerhill:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    image: bunkerhill-alpine:latest
    container_name: bunkerhill
    environment:
    - MONGODB_URL=mongodb://mongodb-service:27017
    - MODE=prod
    links:
    - mongodb:mongodb-service
    depends_on:
    - mongodb
    ports:
    - 3000:3000
    networks:
    - bunkerhill-network
  mongodb:
    image: mongo:3.4.14-jessie 
    container_name: mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - /data/db/mongodb:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
    - bunkerhill-network
networks:
  bunkerhill-network:
