// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bbcyyb/bunkerhill/models"
)

// DeleteBlogOKCode is the HTTP code returned for type DeleteBlogOK
const DeleteBlogOKCode int = 200

/*DeleteBlogOK Successful response

swagger:response deleteBlogOK
*/
type DeleteBlogOK struct {
}

// NewDeleteBlogOK creates DeleteBlogOK with default headers values
func NewDeleteBlogOK() *DeleteBlogOK {

	return &DeleteBlogOK{}
}

// WriteResponse to the client
func (o *DeleteBlogOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteBlogBadRequestCode is the HTTP code returned for type DeleteBlogBadRequest
const DeleteBlogBadRequestCode int = 400

/*DeleteBlogBadRequest Bad Request

swagger:response deleteBlogBadRequest
*/
type DeleteBlogBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewDeleteBlogBadRequest creates DeleteBlogBadRequest with default headers values
func NewDeleteBlogBadRequest() *DeleteBlogBadRequest {

	return &DeleteBlogBadRequest{}
}

// WithPayload adds the payload to the delete blog bad request response
func (o *DeleteBlogBadRequest) WithPayload(payload *models.GenericError) *DeleteBlogBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete blog bad request response
func (o *DeleteBlogBadRequest) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBlogBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBlogInternalServerErrorCode is the HTTP code returned for type DeleteBlogInternalServerError
const DeleteBlogInternalServerErrorCode int = 500

/*DeleteBlogInternalServerError Internal Server Error

swagger:response deleteBlogInternalServerError
*/
type DeleteBlogInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewDeleteBlogInternalServerError creates DeleteBlogInternalServerError with default headers values
func NewDeleteBlogInternalServerError() *DeleteBlogInternalServerError {

	return &DeleteBlogInternalServerError{}
}

// WithPayload adds the payload to the delete blog internal server error response
func (o *DeleteBlogInternalServerError) WithPayload(payload *models.GenericError) *DeleteBlogInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete blog internal server error response
func (o *DeleteBlogInternalServerError) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBlogInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
