// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bbcyyb/bunkerhill/models"
)

// GetBlogByIDOKCode is the HTTP code returned for type GetBlogByIDOK
const GetBlogByIDOKCode int = 200

/*GetBlogByIDOK Successful response

swagger:response getBlogByIdOK
*/
type GetBlogByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Blog `json:"body,omitempty"`
}

// NewGetBlogByIDOK creates GetBlogByIDOK with default headers values
func NewGetBlogByIDOK() *GetBlogByIDOK {

	return &GetBlogByIDOK{}
}

// WithPayload adds the payload to the get blog by Id o k response
func (o *GetBlogByIDOK) WithPayload(payload *models.Blog) *GetBlogByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blog by Id o k response
func (o *GetBlogByIDOK) SetPayload(payload *models.Blog) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlogByIDBadRequestCode is the HTTP code returned for type GetBlogByIDBadRequest
const GetBlogByIDBadRequestCode int = 400

/*GetBlogByIDBadRequest Bad Request

swagger:response getBlogByIdBadRequest
*/
type GetBlogByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewGetBlogByIDBadRequest creates GetBlogByIDBadRequest with default headers values
func NewGetBlogByIDBadRequest() *GetBlogByIDBadRequest {

	return &GetBlogByIDBadRequest{}
}

// WithPayload adds the payload to the get blog by Id bad request response
func (o *GetBlogByIDBadRequest) WithPayload(payload *models.GenericError) *GetBlogByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blog by Id bad request response
func (o *GetBlogByIDBadRequest) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlogByIDInternalServerErrorCode is the HTTP code returned for type GetBlogByIDInternalServerError
const GetBlogByIDInternalServerErrorCode int = 500

/*GetBlogByIDInternalServerError Internal Server Error

swagger:response getBlogByIdInternalServerError
*/
type GetBlogByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewGetBlogByIDInternalServerError creates GetBlogByIDInternalServerError with default headers values
func NewGetBlogByIDInternalServerError() *GetBlogByIDInternalServerError {

	return &GetBlogByIDInternalServerError{}
}

// WithPayload adds the payload to the get blog by Id internal server error response
func (o *GetBlogByIDInternalServerError) WithPayload(payload *models.GenericError) *GetBlogByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blog by Id internal server error response
func (o *GetBlogByIDInternalServerError) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
