// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlogByIDParams creates a new GetBlogByIDParams object
// no default values defined in spec.
func NewGetBlogByIDParams() GetBlogByIDParams {

	return GetBlogByIDParams{}
}

// GetBlogByIDParams contains all the bound params for the get blog by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetBlogById
type GetBlogByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Id of the blog to return
	  Required: true
	  In: path
	*/
	BlogID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBlogByIDParams() beforehand.
func (o *GetBlogByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBlogID, rhkBlogID, _ := route.Params.GetOK("blogId")
	if err := o.bindBlogID(rBlogID, rhkBlogID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBlogByIDParams) bindBlogID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.BlogID = raw

	return nil
}
