// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bbcyyb/bunkerhill/models"
)

// NewUpdateBlogParams creates a new UpdateBlogParams object
// no default values defined in spec.
func NewUpdateBlogParams() UpdateBlogParams {

	return UpdateBlogParams{}
}

// UpdateBlogParams contains all the bound params for the update blog operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateBlog
type UpdateBlogParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Content of blog to be saved
	  Required: true
	  In: body
	*/
	Blog *models.Blog
	/*Id of the blog to update
	  Required: true
	  In: path
	*/
	BlogID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateBlogParams() beforehand.
func (o *UpdateBlogParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Blog
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("blog", "body"))
			} else {
				res = append(res, errors.NewParseError("blog", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Blog = &body
			}
		}
	} else {
		res = append(res, errors.Required("blog", "body"))
	}
	rBlogID, rhkBlogID, _ := route.Params.GetOK("blogId")
	if err := o.bindBlogID(rBlogID, rhkBlogID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateBlogParams) bindBlogID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.BlogID = raw

	return nil
}
