// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bbcyyb/bunkerhill/models"
)

// UpdateBlogOKCode is the HTTP code returned for type UpdateBlogOK
const UpdateBlogOKCode int = 200

/*UpdateBlogOK Successful response

swagger:response updateBlogOK
*/
type UpdateBlogOK struct {

	/*
	  In: Body
	*/
	Payload *models.Blog `json:"body,omitempty"`
}

// NewUpdateBlogOK creates UpdateBlogOK with default headers values
func NewUpdateBlogOK() *UpdateBlogOK {

	return &UpdateBlogOK{}
}

// WithPayload adds the payload to the update blog o k response
func (o *UpdateBlogOK) WithPayload(payload *models.Blog) *UpdateBlogOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update blog o k response
func (o *UpdateBlogOK) SetPayload(payload *models.Blog) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBlogOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBlogBadRequestCode is the HTTP code returned for type UpdateBlogBadRequest
const UpdateBlogBadRequestCode int = 400

/*UpdateBlogBadRequest Bad Request

swagger:response updateBlogBadRequest
*/
type UpdateBlogBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewUpdateBlogBadRequest creates UpdateBlogBadRequest with default headers values
func NewUpdateBlogBadRequest() *UpdateBlogBadRequest {

	return &UpdateBlogBadRequest{}
}

// WithPayload adds the payload to the update blog bad request response
func (o *UpdateBlogBadRequest) WithPayload(payload *models.GenericError) *UpdateBlogBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update blog bad request response
func (o *UpdateBlogBadRequest) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBlogBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBlogInternalServerErrorCode is the HTTP code returned for type UpdateBlogInternalServerError
const UpdateBlogInternalServerErrorCode int = 500

/*UpdateBlogInternalServerError Internal Server Error

swagger:response updateBlogInternalServerError
*/
type UpdateBlogInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GenericError `json:"body,omitempty"`
}

// NewUpdateBlogInternalServerError creates UpdateBlogInternalServerError with default headers values
func NewUpdateBlogInternalServerError() *UpdateBlogInternalServerError {

	return &UpdateBlogInternalServerError{}
}

// WithPayload adds the payload to the update blog internal server error response
func (o *UpdateBlogInternalServerError) WithPayload(payload *models.GenericError) *UpdateBlogInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update blog internal server error response
func (o *UpdateBlogInternalServerError) SetPayload(payload *models.GenericError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBlogInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
