// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Blog blog
// swagger:model blog
type Blog struct {

	// author
	Author *Author `json:"author,omitempty"`

	// body
	Body string `json:"body,omitempty"`

	// body html
	BodyHTML string `json:"body_html,omitempty"`

	// comment ids
	CommentIds []string `json:"comment_ids"`

	// id
	ID string `json:"id,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this blog
func (m *Blog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthor(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCommentIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Blog) validateAuthor(formats strfmt.Registry) error {

	if swag.IsZero(m.Author) { // not required
		return nil
	}

	if m.Author != nil {

		if err := m.Author.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("author")
			}
			return err
		}

	}

	return nil
}

func (m *Blog) validateCommentIds(formats strfmt.Registry) error {

	if swag.IsZero(m.CommentIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Blog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Blog) UnmarshalBinary(b []byte) error {
	var res Blog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
